Repository ralna/spral, pull requests merged in 2024-06, with the labels that each got.

#199 Fix insufficient allocate in SSIDS C interface
  interfaces/C/ssids.f90
Labels: bug, memory-leak

#201 Improve unit tests
  meson.build
Labels: build-system

#212 [CI] Remove Cirrus due to compute limit
  .cirrus.yml
Labels: ci

#216 [CI] Use GitHub Actions to test SPRAL on Apple Silicon
  .github/workflows/meson.yml
Labels: ci
